spring.application.name=flipkart_backend
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:flipkart_db}?createDatabaseIfNotExist=true&ssl-mode=${SSL_MODE:DISABLED}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret
jwt.secret=${JWT_SECRET:MySuperSecretKeyForFlipkartCloneProject123456789}
jwt.expiration=86400000

# Server Port
server.port=8080

# Add Stripe Configuration
stripe.api.key=${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
stripe.success.url=http://localhost:3000/payment-success?sessionId={CHECKOUT_SESSION_ID}
stripe.cancel.url=http://localhost:3000/payment-failure